/** @type {import('tailwindcss').Config} */
module.exports = {
  // NOTE: Update this to include the paths to all files that contain Nativewind classes.
  content: ["./App.tsx", "./components/**/*.{js,jsx,ts,tsx}", "./src/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        primary: "#FF8715",
        secondary: "#6C757D",
        success: "#28A745",
        danger: "#DC3545",
        warning: "#FFC107",
        info: "#17A2B8",
        light: "#F8F9FA",
        dark: "#0F0F0F",
        white: "#FFFFFF",
        black: "#000000",
        gray: "#1B1B1B",
        signOut: "#1D1414",

        // Theme Mode
        themeMode: {
          light: {
            background: "#FFFFFF",
            tabBarBackground: "#FFFFFF",
            iconButton: "#DEE2E6",
            card: "#DEE2E6",
            text: "#000000",
            border: "#DEE2E6",
            notification: "#DC3545",
            gray: "",
          },
          dark: {
            background: "#0F0F0F",
            tabBarBackground: "#0F0F0F",
            iconButton: "#201D1C",
            card: "#201D1C",
            text: "#FFFFFF",
            border: "#495057",
            notification: "#DC3545",
            gray: "#1B1B1B",
          },
        },
      },
      fontFamily: {
        thin: ["Poppins-Thin"],
        regular: ["Poppins-Regular"],
        medium: ["Poppins-Medium"],
        semibold: ["Poppins-SemiBold"],
      },
      fontSize:{
        xs: "9px",
        sm: "11px",
        md: "13px",
        lg: "16px",
        xl: "19px",
        "2xl": "23px",
        "3xl": "28px",
        "4xl": "32px",
        "5xl": "36px",
      },
      width:{
        xs: "4px",
        sm: "8px",
        md: "12px",
        lg: "16px",
        xl: "20px",
        "2xl": "24px",
        "3xl": "28px",
        "4xl": "32px",
        "5xl": "36px",
      },
      height:{
        xs: "4px",
        sm: "8px",
        md: "12px",
        lg: "16px",
        xl: "20px",
        "2xl": "24px",
        "3xl": "28px",
        "4xl": "32px",
        "5xl": "36px",
      },
      padding:{
        xs: "4px",
        sm: "8px",
        md: "12px",
        lg: "16px",
        xl: "20px",
        "2xl": "24px",
        "3xl": "28px",
      },
      gap:{
        xs: "4px",
        sm: "8px",
        md: "12px",
        lg: "16px",
        xl: "20px",
        "2xl": "24px",
        "3xl": "28px",
      },
      borderRadius: {
        xsm: "4px",
        sm: "8px",
        md: "10px",
        lg: "12px",
        xl: "16px",
        "2xl": "20px",
        "3xl": "24px",
      },
      lineHeight:{
        xs: "4px",
        sm: "8px",
        md: "12px",
        lg: "16px",
        xl: "20px",
        "2xl": "24px",
        "3xl": "28px",
      },
      leading:{  
        xs: "4px",
        sm: "8px",
        md: "12px",
        lg: "16px",
        xl: "20px",
        "2xl": "24px",
        "3xl": "28px",
      }
    },
  },
  plugins: [],
}